## 1 - Crie um Dockerfile utilizando a imagem chuanwen/cowsay.
FROM chuanwen/cowsay:latest
## 2 - Defina um ENTRYPOINT para a execução do comando.
ENTRYPOINT ["/usr/games"]
# 3 - Utilize o CMD para definir uma mensagem padrão.
CMD ["Muh!"] 
